# Generated by Django 5.2.16 on 2026-07-25 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timezone', models.TextField(default='Europe/Paris')),
                ('weight_unit', models.TextField(default='kg')),
                ('date_format', models.TextField(default='%Y-%m-%d')),
                ('smoothing_window_days', models.PositiveIntegerField(default=14)),
                ('include_excluded_in_summaries', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_at', models.DateTimeField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muscle_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.TextField(choices=[('manual', 'Manual'), ('import', 'Import')], default='manual')),
                ('notes', models.TextField(blank=True, default='')),
                ('conditions', models.TextField(blank=True, default='')),
                ('is_excluded', models.BooleanField(default=False)),
                ('exclusion_reason', models.TextField(blank=True, default='')),
                ('legacy_payload', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='records.profile')),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['-measured_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('file_hash', models.TextField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.IntegerField()),
                ('accepted_count', models.IntegerField()),
                ('rejected_count', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='records.profile')),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileTarget',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_body_fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_muscle_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='records.profile')),
            ],
            options={
                'db_table': 'profile_targets',
                'ordering': ['-valid_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.TextField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_devices',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sheet', models.TextField(blank=True, default='')),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('status', models.TextField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('skipped', 'Skipped')])),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='records.importbatch')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='records.measurement')),
            ],
            options={
                'db_table': 'measurement_import_rows',
                'indexes': [models.Index(fields=['import_batch', 'source_sheet', 'source_row'], name='measurement_import__3e2113_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['profile', 'measured_at'], name='measurement_profile_bbadb3_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['profile', 'is_excluded', 'measured_at'], name='measurement_profile_563124_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='measurements_weight_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('body_fat_percent__isnull', True), models.Q(('body_fat_percent__gte', 0), ('body_fat_percent__lte', 100)), _connector='OR'), name='measurements_body_fat_range'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('muscle_percent__isnull', True), models.Q(('muscle_percent__gte', 0), ('muscle_percent__lte', 100)), _connector='OR'), name='measurements_muscle_range'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('profile', 'file_hash'), name='import_batches_profile_file_hash_uniq'),
        ),
        migrations.AddConstraint(
            model_name='profiletarget',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='profile_targets_valid_range'),
        ),
    ]
