# Generated by Django 5.2.16 on 2026-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletarget',
            name='body_fat_max_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profiletarget',
            name='body_fat_min_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profiletarget',
            name='muscle_max_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profiletarget',
            name='muscle_min_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profiletarget',
            name='weight_max_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profiletarget',
            name='weight_min_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='profiletarget',
            constraint=models.CheckConstraint(condition=models.Q(('weight_min_kg__isnull', True), ('weight_max_kg__isnull', True), ('weight_min_kg__lte', models.F('weight_max_kg')), _connector='OR'), name='profile_targets_weight_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='profiletarget',
            constraint=models.CheckConstraint(condition=models.Q(('body_fat_min_percent__isnull', True), ('body_fat_max_percent__isnull', True), ('body_fat_min_percent__lte', models.F('body_fat_max_percent')), _connector='OR'), name='profile_targets_fat_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='profiletarget',
            constraint=models.CheckConstraint(condition=models.Q(('muscle_min_percent__isnull', True), ('muscle_max_percent__isnull', True), ('muscle_min_percent__lte', models.F('muscle_max_percent')), _connector='OR'), name='profile_targets_muscle_min_lte_max'),
        ),
    ]
