# Generated by Django 5.x

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_migrate_legacy_target_ranges"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompassPreferences",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("weight_importance", models.DecimalField(decimal_places=2, default=Decimal("0.25"), max_digits=4)),
                ("body_fat_importance", models.DecimalField(decimal_places=2, default=Decimal("0.45"), max_digits=4)),
                ("muscle_importance", models.DecimalField(decimal_places=2, default=Decimal("0.30"), max_digits=4)),
                ("weight_soft_kg", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=5)),
                ("weight_hard_kg", models.DecimalField(decimal_places=2, default=Decimal("3.00"), max_digits=5)),
                ("fat_soft_pp", models.DecimalField(decimal_places=2, default=Decimal("2.00"), max_digits=5)),
                ("fat_hard_pp", models.DecimalField(decimal_places=2, default=Decimal("6.00"), max_digits=5)),
                ("muscle_soft_pp", models.DecimalField(decimal_places=2, default=Decimal("1.50"), max_digits=5)),
                ("muscle_hard_pp", models.DecimalField(decimal_places=2, default=Decimal("4.00"), max_digits=5)),
                ("trend_window_days", models.PositiveIntegerField(default=30)),
                ("comparison_window_days", models.PositiveIntegerField(default=30)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compass_preferences",
                        to="records.profile",
                    ),
                ),
            ],
            options={
                "db_table": "compass_preferences",
            },
        ),
    ]
